import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/mode-toggle"
import Link from "next/link"
import { Button } from "@/components/ui/button"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col min-h-screen">
            <header className="container mx-auto px-4 py-6 flex justify-between items-center">
              <Link href="/" className="text-2xl font-bold">
                Your Logo
              </Link>
              <nav className="flex items-center space-x-4">
                <Link href="/projects" passHref>
                  <Button variant="ghost">Projects</Button>
                </Link>
                <Link href="/about" passHref>
                  <Button variant="ghost">About Me</Button>
                </Link>
                <Link href="/contact" passHref>
                  <Button variant="ghost">Contact</Button>
                </Link>
                <ModeToggle />
              </nav>
            </header>
            <main className="flex-grow">
              {children}
            </main>
            <footer className="container mx-auto px-4 py-6 flex justify-between items-center">
              <div>© {new Date().getFullYear()} Your Name</div>
              <div className="space-x-4">
                <a href="https://linkedin.com/in/yourprofile" target="_blank" rel="noopener noreferrer">LinkedIn</a>
                <a href="https://github.com/yourusername" target="_blank" rel="noopener noreferrer">GitHub</a>
              </div>
            </footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}